# Generated by Django 4.1.2 on 2022-10-26 06:40

from django.db import migrations, models
import story.models
import story.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=story.models.upload_to, validators=[story.validators.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('images', models.ManyToManyField(blank=True, to='story.image')),
            ],
        ),
    ]
